---
title: "Analise Bitcoin"
author: "Christiano Simoes"
date: "2023-12-18"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(crypto2)
library(dplyr)
library(ggplot2)
library(hrbrthemes)
set.seed(1234)

```

## Resumo

A ideia é capturar os dados usando como fonte o binancer. A partir disso, 
calculamos o indice de Mayer(valor do momento do bitcoin dividido pela média móvel
dos últimos 200 dias).   
A decisão é tomada de de acordo com:  
Index < 1 significa "Strong Buy".  
1 < Index < 1.5 Significa esperar um pouco para obersvar o mercado.  
Index > 1.5 Significa vender.  
Index > 2 Venda logo!!.

```{r gettinData, warning=FALSE, message=FALSE, echo=FALSE}
rm(list = ls())
library(binancer)

num_years = 4

loadDF <- read.csv("../data/database_crypto.csv")

lastDate <- as.Date(max(loadDF$X))-3
todayDate <- as.Date(Sys.Date())

rownames(loadDF) <- loadDF$X
loadDF <- loadDF[,-1]
daysLength <- as.numeric(todayDate - lastDate)

if(daysLength >0){
  historical_data <- binance_klines('BTCBRL',
                         interval = '1d',
                         start_time = lastDate,
                         end_time = todayDate)
  # Create a data frame
  crypto_data <- data.frame(
    Open = historical_data$open,
    High = historical_data$high,
    Low = historical_data$low,
    Close = historical_data$close,
    Volume = historical_data$volume
  )
  
  rownames(crypto_data) <- as.Date(historical_data$open_time)
  
  crypto_data <- rbind(crypto_data, loadDF)
  library(dplyr)
  crypto_data$date <- rownames(crypto_data)
  crypto_data <- crypto_data[!duplicated(crypto_data$date),]
  crypto_data <- crypto_data %>% select(Open, High, Low, Close, Volume)
}else{
  crypto_data <- loadDF
}


quantmod::chartSeries(
  x =    head(crypto_data, 200),
  name = 'BTCBRL',
  theme = quantmod::chartTheme('white')
)

quantmod::addMACD()
quantmod::addBBands()

write.csv(crypto_data, "../data/database_crypto.csv", row.names = T)



```

## Calculando o Indice

```{r index, echo=FALSE}
nDays = 200
bitcoin_2023 <- crypto_data
nRange <- nrow(bitcoin_2023)- nDays
index_summary <- data.frame(index = rep(NA, nRange), 
                            date = rep(NA, nRange), 
                            decision = rep(NA, nRange),
                            color = rep(NA,nRange),
                            stop = rep(NA,nRange))
for( i in c(1:nRange)){
  media <- mean(as.vector(bitcoin_2023[i:(i+nDays-1), "Close"]))
  mayers_index <- bitcoin_2023$Close[i]/media
  index_summary$index[i] <- mayers_index
  index_summary$date[i] <- rownames(bitcoin_2023)[i]
  if(mayers_index <= 1){index_summary$decision[i] <- "Strong Buy"; index_summary$color[i] <- "#69b3a2"}
  if(mayers_index > 1 & mayers_index <= 1.5){index_summary$decision[i] <- "Wait to Buy or Sell";  index_summary$color[i] <- "#0000E2"}
  if(mayers_index > 1.5 & mayers_index <= 2){index_summary$decision[i] <- "Sell"; index_summary$color[i] <- "#FF7F00"}
  if(mayers_index > 2){index_summary$decision[i] <- "Strong Sell"; index_summary$color[i] <- "#FF0000"}
  
}

#format method, which is necessary for formating in a data.frame   
format.money  <- function(x, ...) {
  paste0("R$ ", formatC(as.numeric(x), format="f", digits=2, big.mark=","))
}

index_summary$date <- as.Date(index_summary$date)
bitcoin_2023$timestamp <- rownames(bitcoin_2023)
lastDate <- max(bitcoin_2023$timestamp)
todayRate <- binance_avg_price('BTCBRL')
cat(" Last date:", as.character(Sys.Date()), " Multiple Mayer's index is: ", round(index_summary[index_summary$date == Sys.Date(), "index"],2),"\n",
    "Price = ", format.money(todayRate$price),"\n",
    "The decision is: ", index_summary[index_summary$date == Sys.Date(), "decision"], "\n")



```

## Análise Gráfica 4 Anos

```{r grafico, warning=FALSE, echo=FALSE}

# Convert to factor
index_summary$color <- as.factor(index_summary$color)  
index_summary$decision <- as.factor(index_summary$decision)  

index_summary <- index_summary[order(desc(index_summary$date)),]

printPlot <- function(inDays){
  plot_data <- index_summary[1:inDays,]
  
  # Creating Color schema
  unique_colors <- unique(plot_data$color)
  unique_labels <- unique(plot_data$decision)
  p1 <- plot_data %>%
             ggplot(aes(x = date, y = index)) +
             geom_line(color = "grey") +
             geom_hline(yintercept=c(2.0, 1.5, 1.0), linetype="dashed", color = c("red","blue","green")) +
             geom_point(aes(fill = color), shape = 21, color = "black", size = 3) +
             scale_fill_identity(guide = "legend", labels = unique_labels, breaks = unique_colors) +  # Customize legend labels
             theme_ipsum() +
             ggtitle("Evolution of Bitcoin Index (Multiple Mayer 200)")
 
}

plotDays <- 365*num_years
# Show the plot
print(printPlot(plotDays))


```

## Análise Gráfica 1 Ano 

```{r yearPlot, warning=FALSE, echo=FALSE}
# Show the plot
yearDays <- 365
print(printPlot(yearDays))
```


## Análise Gráfica 1 Mês 

```{r monthPlot, warning=FALSE, echo=FALSE}
# Show the plot
monthDays <- 30
print(printPlot(monthDays))
```

